# Generated by Django 6.0.5 on 2026-05-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Employee', 'Normal Employee'), ('Management', 'C-Level / Management'), ('Admin', 'Administrator')], default='Employee', max_length=20),
        ),
    ]
