# Generated by Django 6.0.5 on 2026-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_policydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('ppt', 'PowerPoint Presentation')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('is_new', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
